### ISSUE TITLE
battlelog.battlefield.com login is changed

### ISSUE THREAD

**Issue by OneManArmy-NL** [Pure-Battlefield/PureSeeder3#6]
Hi,

The way to login into battlelog is changed. due the change the in build in firefox does not login automatically as it used to do.

**Comment by SKHecht** [comment]
Do you know how it was changed by any chance? Or just that it broke?

**Comment by OneManArmy-NL** [comment]
Not broke, but they changed a bit how to login with a browser. when the seeder starts you have to manually press the "login" option in the seeder (browser) . when you do the seeder see that you are logged in and will start seeding.

**Comment by ForceTen2112** [comment]
I see on battelog you have to click login and it sends you to different
page. All you need to do is click "login" and then it's fine?

**Comment by RoyDodd** [comment]
Yes, that appears to be the case.

Roy
Panduhh

**Comment by SIothies** [comment]
I haven't been volunteering for PURE in over a year and have no idea how to
remove myself from this mailing list. Could someone please?

Thanks.

**Comment by ForceTen2112** [comment]
I think you have to do it through github.

**Comment by ForceTen2112** [comment]
I fixed the issue and pushed it to github. I believe the app will detect the change and rebuild, but I am not sure and I may have totally fucked that up (sorry, never actually updated the seeder before). I'll look out for any emails if I broke everything.

**Comment by OneManArmy-NL** [comment]
Hi,

it did not work for me. it did not get pushed and i uninstalled the seerder and installed it again but no luck. still the same that it needs to "click" at build in firefox login

**Comment by ForceTen2112** [comment]
Yep, that's what I thought might happen. I'll try and get it deployed
tonight.

On Fri, Jul 10, 2015 at 12:07 PM, OneManArmy-NL <notifications@github.com>
wrote:

> Hi,
>
> it did not work for me. it did not get pushed and i uninstalled the
> seerder and installed it again but no luck. still the same that it needs to
> "click" at build in firefox login
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Pure-Battlefield/PureSeeder3/issues/6#issuecomment-120446130>
> .
>



-- 
Sam Hecht

**Comment by ForceTen2112** [comment]
Fix deployed
